# Toolbar/Menu Items
Toolbar.Name=Designer Plus Plus Toolbar

Action.CSSVariableViewer.Name=CSS Variable Viewer
Action.CSSVariableViewer.Description=View and copy CSS variables

Action.NotePad.Name=NotePad
Action.NotePad.Description=Opens a simple text editor for quick notes

Action.ClearParams.Name=Clear Parameters
Action.ClearParams.Description=Clears all view params and saves them to dev-params.json

Action.SetParams.Name=Set Parameters
Action.SetParams.Description=Sets view params from dev-params.json

Action.SanitizeCustomProps.Name=Sanitize Custom Properties
Action.SanitizeCustomProps.Description=Sanitizes custom properties in the current view by changing persistence and access mode

Action.GatewayScriptConsole.Name=Gateway Script Console
Action.GatewayScriptConsole.Description=Opens a Script Console for advanced scripting and debugging but runs the code in the context of the Gateway